### ISSUE TITLE
vskernels issue list

### ISSUE THREAD

**Issue by ghost** [Jaded-Encoding-Thaumaturgy/vs-kernels#19]
- [x] Make width/height optional arguments to allow 1x resampling with non-interpolatory kernels without manually specifying w/h.
- [ ] #29
- [ ] #30

**Comment by Setsugennoao** [comment]
What's match centers resampling model?

**Comment by LightArrowsEXE** [comment]
> What's match centers resampling model?

https://entropymine.com/imageworsener/matching/
