### ISSUE TITLE
Expand cross conversion shifting params

### ISSUE THREAD

**Issue by LightArrowsEXE** [Jaded-Encoding-Thaumaturgy/vs-kernels#21]
Currently it's not clear to me whether we can really affect the shift introduced during the resampling of interlaced video.

https://github.com/Jaded-Encoding-Thaumaturgy/vs-kernels/blob/73419b2399ce8e1d652bbf07d543245214d9d621/vskernels/kernels/abstract.py#L278-L285

Specifically, some implementations may improperly shift the fields in the same direction (@wiwaz can clarify or correct me here), however currently, to my understanding, there's no way to follow this behaviour, making it impossible to descale it the same way unless you separate the fields yourself. This is rather impractical in certain situations where you have to check different kernels for every frame. Having some kind of way to either override these parameters or toggle between different directions and the same direction would be nice.

**Comment by Setsugennoao** [comment]
Are you asking me to add different shift per field? If so, no; out of scope.

**Comment by wiwaz** [comment]
Not out of scope, per-field src_top adjustment is necessary for this.

**Comment by Setsugennoao** [comment]
then, any decent api you suggest?
