### ISSUE TITLE
Sigmoid Slope somehow causing more haloing

### ISSUE THREAD

**Issue by Vodes** [Jaded-Encoding-Thaumaturgy/vs-kernels#31]
https://slow.pics/c/JK2VJobp from @Ravencentric on the discord.

Possibly useful resources.
https://github.com/Vodes/vodesfunc/commit/abf2dc7eedd1f1d1a6968f9d1a3d2663b908d0b7

https://github.com/Jaded-Encoding-Thaumaturgy/vs-kernels/blob/c53b468f8f27f5909c0ef82a51b01eca6204815f/vskernels/util.py#L174-L178

**Comment by Setsugennoao** [comment]
Should be fixed in https://github.com/Jaded-Encoding-Thaumaturgy/vs-kernels/commit/5316b3dae661d0b424bcb253163c4dcdcd735b0c
