### ISSUE TITLE
AttributeError: type object 'cached' has no attribute 'property'

### ISSUE THREAD

**Issue by shssoichiro** [Jaded-Encoding-Thaumaturgy/vs-kernels#32]
After the most recent commit, any package that depends on `vs-kernels` appears to be throwing an error, `AttributeError: type object 'cached' has no attribute 'property'`. I was able to resolve this locally by changing the four instances of `@inject_self.cached.property` on the `kernel_radius` definitions to `@inject_self.property`.

Python 3.12.0, VS R68, Windows

**Comment by Setsugennoao** [comment]
Update stgpytools
